djangocrud/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    #path('tasks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('servicios', views.servicios, name='servicios'),
    path('sobre_nosotros', views.sobre_nosotros, name='sobre_nosotros'),
    path('completed/', views.completed_tasks, name='completed_tasks'),
    path('complete/<int:task_id>/', views.complete_task, name='complete_task'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    paid_vacation = models.BooleanField(default=False)
    date_range = models.CharField(max_length=100)
    completed_at = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    def __str__(self):
        return self.title

"""
class Task(models.Model): 
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created= models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True , blank=True)
    important= models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        return self.title + 'by' + self.user.username
        """ 

tasks/forms.py
from django.forms import ModelForm
from .models import Task

from django.forms.widgets import DateInput
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }



class TaskForm(forms.ModelForm):
    paid_vacation = forms.BooleanField(required=False, label='Vacaciones pagas')
    date_range = forms.CharField(widget=forms.TextInput(attrs={'type': 'text', 'class': 'daterange'}), label='Rango de fechas')

    class Meta:
        model = Task
        fields = ['title', 'description', 'paid_vacation', 'date_range']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm'}),
            'description': forms.Textarea(attrs={
                'class': 'form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm'}),
        }

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            if not isinstance(field.widget, forms.widgets.DateInput):
                field.widget.attrs.update({'class': 'form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm'})

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import TaskForm
from .models import Task
from django.utils import timezone
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.db.models import Q
# Create your views here.
def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': CustomUserCreationForm()
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'],
                                                password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('tasks')
            except IntegrityError:
                return render(request, 'signup.html', {
                    'form': CustomUserCreationForm(),
                    "error": 'este usuario ya existe'
                })
        return render(request, 'signup.html', {
            'form': CustomUserCreationForm(),
            "error": 'contraseña no coincide'
        })
   

def tasks(request):
    tasks = Task.objects.filter(user=request.user, completed_at__isnull=True)
    return render(request, 'tasks.html', {'tasks': tasks})

def completed_tasks(request):
    tasks = Task.objects.filter(user=request.user,completed_at__isnull=False )
    return render(request, 'completed_tasks.html', {'tasks': tasks})

def complete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.completed_at = timezone.now()
    task.save()
    return redirect('completed_tasks')

def create_task(request):
    if request.method == 'GET':
        return render(request,'create_task.html',{
        'form': TaskForm
        
    })
    else:
        try:
            form = TaskForm(request.POST)
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect('tasks')
        except ValueError:
             return render(request,'create_task.html',{
            'form': TaskForm,
            'error': 'porfavor pruebe con valor valido'
         })
 
def signout(request):
    logout(request)
    return redirect('home')
   
def signin(request):
  if request.method == 'GET': 
        return render(request, 'signin.html', {
        'form': AuthenticationForm
    })
  else:
      user = authenticate(request,username =request.POST['username'], password=request.POST['password'])
      if user is None:
            return render(request, 'signin.html', {
          'form': AuthenticationForm,
          'error': 'Username or password is incorrect'
      })

      else:
          login(request,user)
          return redirect('tasks')
          
def task_detail(request,task_id):
    if request.method == 'GET':
        task =  get_object_or_404(Task,pk=task_id,user=request.user)
        form = TaskForm(instance=task)
        return render(request, 'task_detail.html', {'task': task, 'form': form} )
    else:
        try:
            task = get_object_or_404(Task,pk=task_id, user=request.user)
            form = TaskForm(request.POST, instance=task)
            form.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'task_detail.html', {'task': task, 'form': form, 'Error': 'Error Actualizando'} )



def delete_task(request, task_id):
   task =  get_object_or_404(Task,pk=task_id,user=request.user)
   if request.method == 'POST':
       task.delete()
       return redirect('tasks')

    

def sobre_nosotros(request):
    return render(request, 'sobre_nosotros.html')

def servicios(request):
    return render(request, 'servicios.html')

tasks/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django CRUD</title>

    <script src="//code.tidio.co/yuigh6y88nlgioimptzircilu2hexulb.js" async></script>



</head>
<body>

    <nav class="bg-white md:flex md:items-center md:justify-between fixed w-full h-16 z-10 shadow-xl">
        <div class="h-full flex justify-between items-center mx-24 max-lg:mx-5">
            <!-- LOGO -->
            <div class="text-xl my-auto"><a href="/"><img class="logo" src="../../img/Logo_negro.jpeg" alt=""  >AusentSoft</a></div>
            <!-- LINK DE NAVEGACION -->


            <span class="text-3xl mx-2">
                <ion-icon name="reorder-three-outline" class="cursor-pointer md:hidden block"
                    onclick="Menu(this)"></ion-icon>
            </span>
        </div>
        <ul class="md:flex md:items-center  z-[-1] md:z-auto md:static absolute  w-full left-0 md:w-auto md:py-0 py-4 md:pl-0 pl-7 md:opacity-100 opacity-0 top-[-400px] transition-all ease-in duration-500">
            
            
            <li class="md:ml-0 sm:pl-12 md:pl-12 text-justify lg:pl-0">
                <a href="/" class="mx-4 my-6 md:my-0   hover:text-sky-300  hover:underline hover:duration-500">Inicio</a>
            </li>

            <li class="md:ml-0 sm:pl-12 md:pl-12 text-justify lg:pl-0">
                <a href="/sobre_nosotros" class="mx-4 my-6 md:my-0   hover:text-sky-300  hover:underline hover:duration-500">Sobre Nosotros</a>
            </li>

            <li class="md:ml-0 sm:pl-12 md:pl-12 text-justify lg:pl-0">
                <a href="/servicios" class="mx-4 my-6 md:my-0   hover:text-sky-300  hover:underline hover:duration-500">Productos</a>
            </li>





            {% if user.is_authenticated %}

            <li>
                <a href="/tasks" class="mx-4 my-6 md:my-0 hover:text-sky-300  hover:underline hover:duration-500">Permisos</a>
            </li>
            <li>
                <a href="/tasks/create" class="mx-4 my-6 md:my-0 hover:text-sky-300  hover:underline hover:duration-500">Crear Permiso</a>
            </li>
            <li>
                <a href="/completed/" class="mx-4 my-6 md:my-0 hover:text-sky-300  hover:underline hover:duration-500">Permisos completos</a>
            </li>

            <li>
                <a href="/logout" class="mx-4 my-6 md:my-0 hover:text-sky-300  hover:underline hover:duration-500">Cerrar sesion</a>
            </li>
            {% else %}
            <li>
                <a href="/signup" class="mx-4 my-6 md:my-0 hover:text-sky-300  hover:underline hover:duration-500">Registrar</a>
            </li>

            <li>
                <a href="/signin" class="mx-4 my-6 md:my-0 hover:text-sky-300  hover:underline hover:duration-500">Iniciar sesion</a>
            </li>
            {% endif%}

           
        </ul>
        <!-- BOTONES REGISTRO -->
    </nav>


    {% block content %}
    {% endblock %}


</body>
</html>

tasks/templates/completed_tasks.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Completed Tasks</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body class="font-['Poppins']">
    <header class="text-black font-medium h-1">
        <!-- NAVBAR-->
    </header>

    <main class="flex">
        <div class="flex-1 p-10 mt-[100px]">
            <h1 class="text-2xl font-bold mb-4">Permisos Concedidos</h1>

            <ul>
                {% for task in tasks %}
                <li class="border-b p-4 bg-gray-100 border border-gray-300 rounded-md my-4">
                            <h2 class="text-lg font-semibold">{{ task.title }}</h2>
                            <p>Motivo de solicitud: {{ task.description }}</p>
                            <p>Creada el dia: {{ task.created_at }}</p>
                            <p>Completada el dia: {{ task.completed_at }}</p>
                            <p>Vacaciones Pagas: {{ task.paid_vacation }}</p>
                            <p>Dias solicitados: {{ task.date_range }}</p>
                    <form action="{% url 'delete_task' task.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded">Delete</button>
                    </form>
                </li>
                {% endfor %}
            </ul>
        </div>
    </main>
</body>
</html>
{% endblock %}

tasks/templates/create_task.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Task</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;700&display=swap" rel="stylesheet">

    <!-- Flatpickr CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

</head>

<body class="font-['Poppins']">
    <header class="text-black font-medium h-1">
        <!-- NAVBAR -->
    </header>
    <main>
        <div class="mx-auto max-w-md p-4 bg-white rounded shadow-md">
            <h1 class="mt-[100px] text-black">Create Task</h1>

            {% if error %}
                <p class="text-red-500">{{ error }}</p>
            {% endif %}

            <form action="/tasks/create/" method="POST" class="space-y-4">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_title" class="block text-sm font-medium text-gray-700">Title:</label>
                    {{ form.title }}
                </div>

                <div class="form-group">
                    <label for="id_description" class="block text-sm font-medium text-gray-700">Description:</label>
                    {{ form.description }}
                </div>

                <div class="form-group">
                    <label for="id_paid_vacation" class="block text-sm font-medium text-gray-700">Vacaciones Pagas:</label>
                    {{ form.paid_vacation }}
                </div>

                <div class="form-group">
                    <label for="id_date_range" class="block text-sm font-medium text-gray-700">Rango de Fechas:</label>
                    <input type="text" id="id_date_range" name="date_range" class="form-control">
                </div>

                <button type="submit" class="w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
                    Save
                </button>
            </form>
        </div>

        <!-- Flatpickr JS -->
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                flatpickr('#id_date_range', {
                    mode: 'range',
                    dateFormat: 'Y-m-d',
                    locale: {
                        rangeSeparator: ' to ',
                    }
                });
            });
        </script>
    </main>
</body>

</html>
{% endblock %}

tasks/templates/signin.html
{% extends 'base.html' %}


{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>



    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="style.css">



    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

</head>
<body class=" font-['Poppins'] ">
    <header class="text-black font-medium h-1 ">

        <!-- NAVBAR--> 

    </header>
    <div class="mx-auto max-w-md p-4 bg-white rounded shadow-md my-48">
        <h1 class="text-2xl font-bold mb-4">Login</h1>
    
        {% if error %}
            <p class="text-red-500">{{ error }}</p>
        {% endif %}
    
        <form action="/signin/" method="POST" class="space-y-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username" class="block text-sm font-medium text-gray-700">Username:</label>
                <input type="text" id="id_username" name="username" class="form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm">
            </div>
            
            <div class="form-group">
                <label for="id_password" class="block text-sm font-medium text-gray-700">Password:</label>
                <input type="password" id="id_password" name="password" class="form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm">
            </div>
    
            <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Signin
            </button>
        </form>
    </div>
    {% endblock %}

tasks/templates/signup.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title %}Signup{% endblock %}

{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>



    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="style.css">



    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

</head>

<div class="h-screen w-scren">
    <div class="mx-auto max-w-md p-4 bg-white rounded shadow-md">
    <h1 class="text-2xl font-bold mb-4 mt-[100px]">Signup</h1>

    {% if error %}
        <p class="text-red-500">{{ error }}</p>
    {% endif %}

    <form action="/signup/" method="POST" class="space-y-4">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_username" class="block text-sm font-medium text-gray-700">Username:</label>
            {{ form.username|add_class:"form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" }}
        </div>

        <div class="form-group">
            <label for="id_password1" class="block text-sm font-medium text-gray-700">Password:</label>
            {{ form.password1|add_class:"form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" }}
            <small class="form-text text-muted text-gray-500">
                {{ form.password1.help_text }}
            </small>
        </div>

        <div class="form-group">
            <label for="id_password2" class="block text-sm font-medium text-gray-700">Password confirmation:</label>
            {{ form.password2|add_class:"form-control block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" }}
            <small class="form-text text-muted text-gray-500">
                Enter the same password as before, for verification.
            </small>
        </div>

        <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Registrar
        </button>
    </form>
    </div>
</div>
{% endblock %}

tasks/templates/task_detail.html
{% extends 'base.html' %}

{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>



    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="style.css">



    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

</head>
<body class=" font-['Poppins'] ">
    <header class="text-black font-medium h-1 ">

        <!-- NAVBAR--> 

    </header>
    <div class="mx-auto max-w-md p-4 bg-white rounded shadow-md">
        <h1 class="mt-4 text-2xl font-bold mb-4">{{ task.title }}</h1>
    
        <p class="text-gray-600">Creado por: {{ task.user.username }}</p>

    
        {% if error %}
            <p class="text-red-500">{{ error }}</p>
        {% endif %}
    
        <form method="POST" class="space-y-4">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
                Enviar
            </button>
        </form>
    
        <form action="{% url 'complete_task' task.id %}" method="POST" class="mt-4">
            {% csrf_token %}
            <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Completado
            </button>
        </form>
    
        <form action="{% url 'delete_task' task.id %}" method="POST" class="mt-4">
            {% csrf_token %}
            <button type="submit" class="w-full bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                Eliminar
            </button>
        </form>
    </div>
{% endblock %}

tasks/templates/tasks.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="style.css">

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body class="font-['Poppins']">
    <header class="text-black font-medium h-1">
        <!-- NAVBAR-->
    </header>

    <main class="flex">

        <div class="flex-1 p-10 mt-[100px]">
            <h1 class="text-2xl font-bold mb-4">Tus Permisos</h1>

            <ul>
                {% for task in tasks %}
                    <li class="border-b p-4 bg-gray-100 border border-gray-300 rounded-md my-4 hover:text-sky-500">
                        <span class="relative group cursor-pointer">
                            <a href="{% url 'task_detail' task.id %}">
                                <h2 class="text-lg font-semibold">{{ task.title }}</h2>
                                <p>Motivo de solicitud: {{ task.description }}</p>
                                <p>Creada el dia: {{ task.created_at }}</p>
                                <p>Ultima actualizacion: {{ task.updated_at }}</p>
                                <p>Vacaciones Pagas: {{ task.paid_vacation }}</p>
                                <p>Dias solicitados: {{ task.date_range }}</p>
                                <span class="absolute left-0 -top-6 bg-gray-800 text-white text-sm font-bold py-1 px-2 rounded opacity-0 group-hover:opacity-100 transition-opacity duration-300">Editar</span>
                            </a>
                        </span>
                        <form action="{% url 'complete_task' task.id %}" method="POST" class="inline">
                            {% csrf_token %}
                            <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded my-2">Complete</button>
                        </form>
                        <form action="{% url 'delete_task' task.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded">Delete</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </main>
</body>
</html>
{% endblock %}